const addAppTypes ={
    SET_COMPANY_NAME: 'SET_COMPANY_NAME',
    SET_POSITION_NAME: 'SET_POSITION_NAME',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_SHOW_INTERVIEW: 'SET_SHOW_INTERVIEW',
    SET_INTERVIEW_DATE: 'SET_INTERVIEW_DATE'
}

export default addAppTypes;